In [ ]:
# Fixtures and player analysis
# Author: Marijse

In [2]:
# import the necessary packages
import xml.etree.ElementTree as ET
import pandas as pd
import numpy as np
import psycopg2
import sqlalchemy
from sqlalchemy import create_engine
import glob
from datetime import datetime

import matplotlib.pyplot as plt

pd.set_option('max_columns', 140)
pd.set_option('max_rows', 50)

In [3]:
# Set up the database connection wiht Psycopg2
db = psycopg2.connect(dbname='r7', user='postgres')
cursor=db.cursor()

# Set up a database connection using sqlalchemy
engine = create_engine('postgres://postgres:postgres@localhost:5432/r7')

In [4]:
# Define variables

# Define the input and output strings
input_string = '../_4_data_extracts/squad/'
output_strig = '../_6_data_clean/'

# Define schemas
schema1 = '_0_original_data'
schema2 = '_1_data_views'

### Load data

In [56]:
# load the data from psql
df = pd.read_sql_query("SELECT * FROM " + schema1 + ".match_fixtures",db)

In [57]:
# Drop columns without data
df = df.drop({'index','stage','attendance'},axis=1)

In [58]:
# Plot scores of the different teams by the match number
df = df.sort_values(by=['tournament_id','matchid'],ascending = True)

In [59]:
# We set a number of columns to be integers
int_col = ['matchnumber','team1score','team2score']
for k in int_col:
    df[k] = df[k].astype(int)

In [63]:
df

,city,eventname,gmtdifference,group,kickoff,matchid,matchnumber,stadium,status,team1id,team1name,team1score,team2id,team2name,team2score,tournament_id
630,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,A,2015-12-04T09:00:00,22808,1,The Sevens,Match Completed,2413,Fiji 7s,63,2410,Canada 7s,14,1611
631,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,A,2015-12-04T09:22:00,22809,2,The Sevens,Match Completed,2408,Argentina 7s,31,2423,Japan 7s,19,1611
632,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,B,2015-12-04T09:44:00,22810,3,The Sevens,Match Completed,2420,South Africa 7s,33,2418,Samoa 7s,7,1611
633,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,B,2015-12-04T10:06:00,22811,4,The Sevens,Match Completed,2419,Scotland 7s,17,3911,Russia 7s,14,1611
634,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,C,2015-12-04T10:30:00,22812,5,The Sevens,Match Completed,2416,New Zealand 7s,21,2414,France 7s,14,1611
635,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,C,2015-12-04T10:52:00,22813,6,The Sevens,Match Completed,2422,USA 7s,45,3910,Portugal 7s,14,1611
636,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,D,2015-12-04T11:14:00,22814,7,The Sevens,Match Completed,2412,England 7s,26,3921,Wales 7s,5,1611
637,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,D,2015-12-04T11:36:00,22815,8,The Sevens,Match Completed,2409,Australia 7s,14,2415,Kenya 7s,12,1611
638,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,A,2015-12-04T12:00:00,22816,9,The Sevens,Match Completed,2413,Fiji 7s,21,2423,Japan 7s,17,1611
639,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,A,2015-12-04T12:22:00,22817,10,The Sevens,Match Completed,2408,Argentina 7s,19,2410,Canada 7s,14,1611
640,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,B,2015-12-04T12:44:00,22818,11,The Sevens,Match Completed,2420,South Africa 7s,45,3911,Russia 7s,0,1611
641,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,B,2015-12-04T13:06:00,22819,12,The Sevens,Match Completed,2419,Scotland 7s,12,2418,Samoa 7s,17,1611
642,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,C,2015-12-04T14:14:00,22820,13,The Sevens,Match Completed,2416,New Zealand 7s,47,3910,Portugal 7s,5,1611
643,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,C,2015-12-04T14:36:00,22821,14,The Sevens,Match Completed,2422,USA 7s,21,2414,France 7s,26,1611
644,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,D,2015-12-04T14:58:00,22822,15,The Sevens,Match Completed,2412,England 7s,19,2415,Kenya 7s,12,1611
645,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,D,2015-12-04T15:20:00,22823,16,The Sevens,Match Completed,2409,Australia 7s,43,3921,Wales 7s,0,1611
646,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,A,2015-12-04T18:06:00,22824,17,The Sevens,Match Completed,2410,Canada 7s,7,2423,Japan 7s,21,1611
647,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,A,2015-12-04T18:28:00,22825,18,The Sevens,Match Completed,2413,Fiji 7s,28,2408,Argentina 7s,0,1611
648,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,B,2015-12-04T18:50:00,22826,19,The Sevens,Match Completed,2418,Samoa 7s,19,3911,Russia 7s,10,1611
649,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,B,2015-12-04T19:12:00,22827,20,The Sevens,Match Completed,2420,South Africa 7s,26,2419,Scotland 7s,12,1611
650,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,C,2015-12-04T19:36:00,22828,21,The Sevens,Match Completed,2414,France 7s,35,3910,Portugal 7s,7,1611
651,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,C,2015-12-04T19:58:00,22829,22,The Sevens,Match Completed,2416,New Zealand 7s,12,2422,USA 7s,14,1611
652,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,D,2015-12-04T20:20:00,22830,23,The Sevens,Match Completed,3921,Wales 7s,12,2415,Kenya 7s,10,1611
653,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,D,2015-12-04T20:42:00,22831,24,The Sevens,Match Completed,2412,England 7s,21,2409,Australia 7s,5,1611
654,Dubai,2015/16 HSBC World Rugby Sevens Series - Dubai,4.0,None,2015-12-05T09:30:00,22832,25,The Sevens,Match Completed,2423,Japan 7s,12,2415,Kenya 7s,17,1611
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,A,2017-05-20T17:10:00,24923,21,Twickenham,Match Completed,3921,Wales 7s,17,2415,Kenya 7s,28,1693
246,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,A,2017-05-20T17:32:00,24924,22,Twickenham,Match Completed,2420,South Africa 7s,12,2422,USA 7s,24,1693
247,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,D,2017-05-20T17:54:00,24925,23,Twickenham,Match Completed,2409,Australia 7s,50,3913,Spain 7s,0,1693
248,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,D,2017-05-20T18:16:00,24926,24,Twickenham,Match Completed,2412,England 7s,24,2418,Samoa 7s,19,1693
249,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T09:30:00,24927,25,Twickenham,Match Completed,2415,Kenya 7s,33,3913,Spain 7s,7,1693
250,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T09:52:00,24928,26,Twickenham,Match Completed,2413,Fiji 7s,31,3911,Russia 7s,5,1693
251,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T10:14:00,24929,27,Twickenham,Match Completed,2418,Samoa 7s,21,3921,Wales 7s,29,1693
252,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T10:36:00,24930,28,Twickenham,Match Completed,2414,France 7s,22,2423,Japan 7s,5,1693
253,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T10:58:00,24931,29,Twickenham,Match Completed,2422,USA 7s,31,2409,Australia 7s,14,1693
254,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T11:20:00,24932,30,Twickenham,Match Completed,2416,New Zealand 7s,21,2419,Scotland 7s,24,1693
255,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T11:42:00,24933,31,Twickenham,Match Completed,2412,England 7s,17,2420,South Africa 7s,12,1693
256,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T12:04:00,24934,32,Twickenham,Match Completed,2408,Argentina 7s,7,2410,Canada 7s,28,1693
257,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T12:36:00,24935,33,Twickenham,Match Completed,3913,Spain 7s,5,3911,Russia 7s,38,1693
258,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T12:58:00,24936,34,Twickenham,Match Completed,2418,Samoa 7s,33,2423,Japan 7s,7,1693
259,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T13:20:00,24937,35,Twickenham,Match Completed,2415,Kenya 7s,5,2413,Fiji 7s,45,1693
260,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T13:42:00,24938,36,Twickenham,Match Completed,3921,Wales 7s,26,2414,France 7s,17,1693
261,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T14:04:00,24939,37,Twickenham,Match Completed,2409,Australia 7s,40,2416,New Zealand 7s,7,1693
262,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T14:26:00,24940,38,Twickenham,Match Completed,2420,South Africa 7s,24,2408,Argentina 7s,7,1693
263,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T14:48:00,24941,39,Twickenham,Match Completed,2422,USA 7s,14,2419,Scotland 7s,21,1693
264,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T15:10:00,24942,40,Twickenham,Match Completed,2412,England 7s,24,2410,Canada 7s,5,1693
265,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T16:07:00,24943,41,Twickenham,Match Completed,3911,Russia 7s,19,2418,Samoa 7s,24,1693
266,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T16:32:00,24944,42,Twickenham,Match Completed,2413,Fiji 7s,26,3921,Wales 7s,14,1693
267,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T17:07:00,24945,43,Twickenham,Match Completed,2409,Australia 7s,17,2420,South Africa 7s,28,1693
268,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T17:32:00,24946,44,Twickenham,Match Completed,2422,USA 7s,19,2410,Canada 7s,22,1693
269,London,HSBC World Rugby Sevens Series 2016-17- London,1.0,None,2017-05-21T17:57:00,24947,45,Twickenham,Match Completed,2419,Scotland 7s,12,2412,England 7s,7,1693

In [71]:
# Select all games played by South Africa
saf1 = df[df['team1id']=='2420']
saf1 = saf1[['eventname','matchnumber','team1score']]
#saf1 = saf1.groupby(['eventname'])['team1score'].agg(['count','sum'])
saf2 = df[df['team2id']=='2420']
saf2 = saf2[['eventname','matchnumber','team2score']]
#saf2 = saf2.groupby(['eventname'])['team2score'].agg(['count','sum'])
saf = pd.merge(left = saf1, right = saf2, on='eventname', how='left')
saf= saf.rename(columns = {'matchnumber_x':'matchnumber_team1','matchnumber_y':'matchnumber_team2'})#.reset_index(drop=False)
saf.head()

,eventname,matchnumber_team1,team1score,matchnumber_team2,team2score
0,2015/16 HSBC World Rugby Sevens Series - Dubai,3,33,38.0,26.0
1,2015/16 HSBC World Rugby Sevens Series - Dubai,3,33,43.0,19.0
2,2015/16 HSBC World Rugby Sevens Series - Dubai,11,45,38.0,26.0
3,2015/16 HSBC World Rugby Sevens Series - Dubai,11,45,43.0,19.0
4,2015/16 HSBC World Rugby Sevens Series - Dubai,20,26,38.0,26.0

In [74]:
saf_grouped = saf.groupby(['eventname'])['team1score','team2score'].agg(['count','sum'])

#saf_grouped['score_per_match_team1'] = saf_grouped['points_scored_as_team1'] / saf['game_count_as_team1']
#saf_grouped['score_per_match_team2'] = saf_grouped['points_scored_as_team2'] / saf['game_count_as_team2']
saf_grouped

                                                   team1score      team2score  \
                                                        count  sum      count
eventname
2015/16 HSBC World Rugby Sevens Series - Cape Town          9  201          9
2015/16 HSBC World Rugby Sevens Series - Dubai              8  246          8
2015/16 HSBC World Rugby Sevens Series - Hong Kong          8  218          8
2015/16 HSBC World Rugby Sevens Series - Las Vegas          5  124          5
2015/16 HSBC World Rugby Sevens Series - London             5  108          5
2015/16 HSBC World Rugby Sevens Series - Paris              5  112          5
2015/16 HSBC World Rugby Sevens Series - Singapore          5  108          5
2015/16 HSBC World Rugby Sevens Series - Sydney             8  250          8
2015/16 HSBC World Rugby Sevens Series - Vancouver          5  141          5
2015/16 HSBC World Rugby Sevens Series - Wellin...          8  254          8
HSBC World Rugby Sevens Series 2016-17- Cape Town           6  162          0
HSBC World Rugby Sevens Series 2016-17- Hong Kong           8  198          8
HSBC World Rugby Sevens Series 2016-17- Las Vegas           6  134          0
HSBC World Rugby Sevens Series 2016-17- London              8  120          8
HSBC World Rugby Sevens Series 2016-17- Paris               9  219          9
HSBC World Rugby Sevens Series 2016-17- SIngapore           8  172          8
HSBC World Rugby Sevens Series 2016-17- Sydney              8  174          8
HSBC World Rugby Sevens Series 2016-17- Vancouver           6  117          0
HSBC World Rugby Sevens Series 2016-17- Wellington          8  274          8


                                                      sum
eventname
2015/16 HSBC World Rugby Sevens Series - Cape Town  168.0
2015/16 HSBC World Rugby Sevens Series - Dubai      180.0
2015/16 HSBC World Rugby Sevens Series - Hong Kong  140.0
2015/16 HSBC World Rugby Sevens Series - Las Vegas  105.0
2015/16 HSBC World Rugby Sevens Series - London     110.0
2015/16 HSBC World Rugby Sevens Series - Paris      145.0
2015/16 HSBC World Rugby Sevens Series - Singapore  105.0
2015/16 HSBC World Rugby Sevens Series - Sydney      76.0
2015/16 HSBC World Rugby Sevens Series - Vancouver  155.0
2015/16 HSBC World Rugby Sevens Series - Wellin...  188.0
HSBC World Rugby Sevens Series 2016-17- Cape Town     NaN
HSBC World Rugby Sevens Series 2016-17- Hong Kong   116.0
HSBC World Rugby Sevens Series 2016-17- Las Vegas     NaN
HSBC World Rugby Sevens Series 2016-17- London      160.0
HSBC World Rugby Sevens Series 2016-17- Paris       174.0
HSBC World Rugby Sevens Series 2016-17- SIngapore   144.0
HSBC World Rugby Sevens Series 2016-17- Sydney      200.0
HSBC World Rugby Sevens Series 2016-17- Vancouver     NaN
HSBC World Rugby Sevens Series 2016-17- Wellington  188.0